remote_theme: b2a3e8/jekyll-theme-console

title: 'fcensec.tk'
description: "Hacking club"

header_pages:
  - index.md
  - contacto.md

style: dark

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'
